---
title: "analysis.Rmd"
output: html_document
date: "2024-05-14"
---
#This analysis is for the second experiment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
source("helpers.R")
library(stringr)
library(cluster)

library(factoextra)
library(NbClust)
library(cluster)
```

```{r}
DisjunctiveData <- read_csv("disjunction_02_alln_production_sandbox-merged.csv")
```

```{r}
ThirdSGCeilingParticipant <- DisjunctiveData %>% 
  filter(cond == "3S") %>% 
  mutate(response_binary = ifelse(response == "['is']",1,0)) %>% 
  group_by(cond,workerid) %>% 
  summarize(
    isRate = mean(response_binary),
    CI.Low = ci.low(response_binary),
    CI.High = ci.high(response_binary),
    tokens = n()) %>% 
  mutate(YMin = isRate - CI.Low, YMax = isRate + CI.High)
```

```{r}
FirstSGCeilingParticipant <- DisjunctiveData %>% 
  filter(cond == "1S") %>% 
  mutate(response_binary = ifelse(response == "['am']",1,0)) %>% 
  group_by(cond,workerid) %>% 
  summarize(
    amRate = mean(response_binary),
    CI.Low = ci.low(response_binary),
    CI.High = ci.high(response_binary),
    tokens = n()) %>% 
  mutate(YMin = amRate - CI.Low, YMax = amRate + CI.High)
```

```{r}
PluralCeilingParticipant <- DisjunctiveData %>% 
  filter(str_detect(dataType, "filler_are")) %>% 
  mutate(response_binary = ifelse(response == "['are']",1,0)) %>% 
  group_by(dataType,workerid) %>% 
  summarize(
    areRate = mean(response_binary),
    CI.Low = ci.low(response_binary),
    CI.High = ci.high(response_binary),
    tokens = n()) %>% 
  mutate(YMin = areRate - CI.Low, YMax = areRate + CI.High)
```

```{r}
DisjunctiveCriticalData <- DisjunctiveData %>% 
  filter(dataType == "critical")
```

```{r}
DisjunctiveParticipant <- DisjunctiveCriticalData %>%
  group_by(cond, response,workerid) %>%
  summarize(count = n()) %>%
  group_by(cond) %>%
  mutate(proportion = count / sum(count))
```

```{r}
DisjunctiveCriticalData %>%
  group_by(cond, response,workerid) %>%
  summarize(count = n()) %>%
  group_by(cond) %>%
  mutate(proportion = count / sum(count)) %>%
  ggplot(aes(x = response, y = proportion, fill=response)) +
  geom_bar(stat = "identity", position = position_dodge(preserve = "single")) +
  labs(title = "Proportional Side-by-Side Bar Chart by Type of Response", y = "Proportion") + 
  scale_fill_brewer(palette = "Pastel2") + 
  theme_bw() + 
  facet_grid(workerid~cond)
```

```{r}
DistDf <- DisjunctiveCriticalData %>% 
  select(c("workerid","cond","response")) %>%
  filter(response != '[\'am\']') %>%
  mutate(
    is_are = ifelse(response == '[\'are\']',1,0),
    is_is = ifelse(response == '[\'is\']',1,0),
    # is_am = ifelse(response == '[\'am\']',1,0)
  ) %>% 
  select(-response) %>% 
  group_by(workerid,cond) %>% 
  summarize_all(mean) %>% 
  pivot_wider(names_from = cond, values_from = starts_with("is_"))


response_vectors <- DistDf[ ,-1]
workerid <- DistDf$workerid

wss <- sapply(1:9, function(k) {
  kmeans_result <- kmeans(response_vectors, centers = k)
  kmeans_result$tot.withinss
})

# Plot the elbow curve
plot(1:9, wss, type = "b", pch = 19, frame = FALSE,
     xlab = "Number of Clusters",
     ylab = "Total Within-cluster Sum of Squares")

#Silhouette method
fviz_nbclust(response_vectors, kmeans, method = "silhouette", k.max=9)+
  labs(subtitle = "Silhouette method")

```

```{r}

# Perform k-means clustering
kmeans_result <- kmeans(response_vectors, centers = 4)

# Get cluster labels for each workerid
cluster_labels <- as.factor(kmeans_result$cluster)

# Combine cluster labels with workerid
clustered_workerid <- data.frame(workerid, cluster_labels)

#calculate distance scores 
distances <- apply(response_vectors, 1, function(x) sqrt(rowSums((x - kmeans_result$centers)^2)))
# Option 1: Calculate a score as the inverse of the distance (smaller distance = higher score)
#likelihood_scores <- 1 / distances

# Option 2: Use distance as score (greater distance = higher score)
likelihood_scores <- distances

# Transpose the likelihood_scores matrix to get scores for each workerid
worker_scores <- t(likelihood_scores)

# Create a data frame with workerid and the three scores
worker_scores_df <- data.frame(workerid, worker_scores)

# Print the worker scores
print(worker_scores_df)

merged_data <- DisjunctiveParticipant %>% 
  left_join(clustered_workerid, by = "workerid") %>%
  left_join(worker_scores_df, by = "workerid")
merged_data <- na.omit(merged_data)

averaged_responses <- merged_data %>%
  group_by(condition, cluster_labels, response) %>%
  summarize(mean_proportion = mean(proportion), 
            CI.Low = ci.low(proportion),
            CI.High = ci.high(proportion))%>%
   mutate(YMin = mean_proportion - CI.Low, YMax = mean_proportion + CI.High)

# Plot the clustering result as a bar plot
ggplot(averaged_responses, aes(x = response, y = mean_proportion, fill = response)) +
  geom_bar(stat = "identity", position = "dodge") +
  # scale_fill_manual(values = cbPalette) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax), width=.25) + 
  labs(x = "Response Copula",
       y = "Proportion of Copula Realization") +
  # coord_flip() + 
  facet_grid(cluster_labels~condition) +
  theme_bw()
```


### For Hierarchical Clustering analysis
```{r}
cols_to_convert <- setdiff(names(DistDf),"workerid")
DistDf[cols_to_convert] <- lapply(DistDf[cols_to_convert], as.numeric)

dissim <- daisy(DistDf[,-1])

agg.clust.c <- hclust(dissim,method="single")

plot(agg.clust.c,
     main="Agglomerative, complete linkages")

  # mutate(
  #   is_1P_or_1S = ifelse(condition == '1P_or_1S',1,0),
  #   is_1P_or_3P = ifelse(condition == '1P_or_3P',1,0),
  #   is_1P_or_3S = ifelse(condition == '1P_or_3S',1,0),
  #   is_1S_or_1P = ifelse(condition == '1S_or_1P',1,0),
  #   is_1S_or_3P = ifelse(condition == '1S_or_3P',1,0),
  #   is_1S_or_3S = ifelse(condition == '1S_or_3S',1,0),
  #   is_3P_or_1P = ifelse(condition == '3P_or_1P',1,0),
  #   is_3P_or_1S = ifelse(condition == '3P_or_1S',1,0),
  #   is_3P_or_3S = ifelse(condition == '3P_or_3S',1,0),
  #   is_3S_or_1P = ifelse(condition == '3S_or_1P',1,0),
  #   is_3S_or_1S = ifelse(condition == '3S_or_1S',1,0),
  #   is_3S_or_3P = ifelse(condition == '3S_or_3P',1,0)
  # ) %>% 
  # select(-condition)

# dist_matrix <- daisy(DistDf[, -1], metric = "gower")
```

